// Generated by scripts/sign-green-catalog.mjs. Never commit a private key.
export const GREEN_CATALOG_PUBLIC_KEY = "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAWagG4imMVmGKgusXc3vRpRi9FtRmSnxSHEIkqBybXCo=\n-----END PUBLIC KEY-----\n" as const
export const GREEN_CATALOG_SIGNATURE = "hx8kEtyfzF5gldU7ITaIcnivbyHcN4zgGFhDDVWVmHp5icSlNnPivwQoUdQszKEle2lJ2bQEa5FLeRaNBfsoBQ==" as const
