import type { Metadata } from "next"
import Link from "next/link"
import { ArrowDown, ArrowRight, ArrowUp, Minus, RadioTower, ShieldCheck, TrendingUp } from "lucide-react"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { isDemoQuery } from "@/lib/demo/runtime"
import { getPublicMashupsIndex } from "@/lib/domination/service"

export const metadata: Metadata = { title: "The Mashups Index", description: "A weekly, evidence-ranked index of independent tracks generating credible creator and listener lift.", alternates: { canonical: "/index" } }

export default async function MashupsIndexPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const query = await searchParams
  const demo = isDemoQuery(typeof query.demo === "string" ? query.demo : null)
  const entries = await getPublicMashupsIndex(demo)
  const leader = entries[0]

  return <main className="index-page overflow-hidden pt-[68px]">
    <div className="border-b border-foreground bg-primary px-4 py-2 text-primary-foreground"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-4 font-mono text-[10px] font-bold uppercase tracking-[0.16em]"><span>Independent breakout intelligence</span><span>{demo ? "Simulation / methodology-real" : "Latest published edition"}</span></div></div>
    <section className="mx-auto max-w-[1500px] px-4 pb-28 sm:px-6">
      <header className="relative grid border-x border-b border-foreground lg:grid-cols-12"><div className="index-scan absolute inset-0 opacity-25" /><div className="relative p-6 sm:p-10 lg:col-span-9 lg:p-14"><div className="flex flex-wrap items-center gap-3"><p className="signal-label">Mashups weekly signal</p><Badge variant="outline" className="rounded-none">M/X 001</Badge></div><h1 className="display-type mt-10 text-[clamp(5rem,14vw,13rem)] leading-[0.68] tracking-[-0.075em]">THE<br /><span className="text-primary">INDEX.</span></h1><p className="mt-10 max-w-2xl text-lg leading-relaxed text-muted-foreground sm:text-xl">Not streams. Not follower count. A weekly ranking of independent tracks producing verified creator reproduction and incremental listener intent.</p></div><aside className="relative flex flex-col justify-between border-t border-foreground bg-secondary p-6 lg:col-span-3 lg:border-l lg:border-t-0 sm:p-8"><RadioTower className="size-8" /><div className="my-16"><p className="mono-label">Top signal</p><p className="display-type mt-5 text-6xl">{leader ? Math.round(leader.breakoutScore) : "--"}</p><p className="mt-2 font-semibold">{leader?.trackTitle ?? "Awaiting edition"}</p><p className="text-sm text-muted-foreground">{leader?.artistName ?? "No published evidence yet"}</p></div><p className="text-xs leading-relaxed">Rankings require rights standing, trust-adjusted evidence, and matched campaign measurement.</p></aside></header>

      {entries.length ? <section className="border-x border-b border-foreground"><div className="hidden grid-cols-[5rem_1.4fr_0.7fr_0.8fr_0.7fr_4rem] border-b border-foreground bg-foreground px-5 py-3 font-mono text-[10px] uppercase tracking-widest text-background md:grid"><span>Rank</span><span>Track / artist</span><span>Breakout</span><span>Creator K</span><span>Lift</span><span>Move</span></div>{entries.map((entry, index) => <article key={entry.slug} className="group grid border-b border-foreground last:border-b-0 md:grid-cols-[5rem_1.4fr_0.7fr_0.8fr_0.7fr_4rem]"><div className="grid min-h-24 place-items-center border-b border-foreground bg-card p-4 md:border-b-0 md:border-r"><span className="display-type text-5xl text-primary">{String(entry.rank).padStart(2, "0")}</span></div><div className="p-5 md:border-r"><p className="text-2xl font-semibold">{entry.trackTitle}</p><p className="mt-1 font-mono text-[10px] uppercase tracking-widest text-muted-foreground">{entry.artistName} / {entry.genre}</p><p className="mt-5 text-xs text-muted-foreground">Best cell: {entry.strongestCity} / hook {entry.strongestHookSec}s</p></div><IndexCell label="Breakout" value={Math.round(entry.breakoutScore).toString()} emph={index === 0} /><IndexCell label="Creator K" value={`${entry.creatorKFactor.toFixed(2)}x`} /><IndexCell label="Save lift" value={`+${Math.round(entry.incrementalSaveLift * 100)}%`} /><div className="flex items-center justify-center gap-2 p-4 font-mono text-sm">{entry.movement > 0 ? <ArrowUp className="size-4 text-primary" /> : entry.movement < 0 ? <ArrowDown className="size-4" /> : <Minus className="size-4" />}{Math.abs(entry.movement)}</div></article>)}</section> : <section className="grid min-h-80 place-items-center border-x border-b border-foreground p-8 text-center"><div><TrendingUp className="mx-auto size-10 text-primary" /><h2 className="display-type mt-6 text-5xl">THE FIRST EDITION<br />IS CALCULATING.</h2><p className="mt-4 text-muted-foreground">Only published, evidence-qualified campaigns enter the index.</p><Button className="mt-7" asChild><Link href="/index?demo=1">Inspect labeled edition<ArrowRight /></Link></Button></div></section>}

      <section className="grid border-x border-b border-foreground bg-foreground text-background lg:grid-cols-[1fr_1fr]"><div className="p-6 sm:p-10 lg:border-r lg:border-background/30"><p className="mono-label text-secondary">Method / mashups-index-v1</p><h2 className="display-type mt-6 text-5xl">EVIDENCE BEFORE<br />ENTHUSIASM.</h2><p className="mt-6 max-w-xl leading-relaxed text-background/65">Breakout score combines credible incremental lift, creator reproduction, trust standing, qualified activations, and downstream saves. Paid reach cannot buy rank.</p></div><div className="grid grid-cols-2 gap-px bg-background/30"><MethodCell value="30%" label="Incremental lift" /><MethodCell value="25%" label="Creator K" /><MethodCell value="25%" label="Trust + rights" /><MethodCell value="20%" label="Qualified intent" /></div></section>
      <div className="flex flex-wrap items-center justify-between gap-5 border-x border-b border-foreground bg-secondary p-5 sm:p-7"><p className="flex items-center gap-3 font-semibold"><ShieldCheck className="size-5" />Every ranking ships with an evidence manifest.</p><Button variant="outline" asChild><Link href="/supply?demo=1">Submit independent catalog<ArrowRight /></Link></Button></div>
    </section>
  </main>
}

function IndexCell({ label, value, emph = false }: { label: string; value: string; emph?: boolean }) { return <div className={`flex flex-row items-center justify-between border-t border-foreground p-4 md:flex-col md:items-start md:justify-center md:border-r md:border-t-0 ${emph ? "bg-secondary" : ""}`}><span className="font-mono text-[9px] uppercase tracking-widest text-muted-foreground md:hidden">{label}</span><strong className="display-type text-4xl">{value}</strong></div> }
function MethodCell({ value, label }: { value: string; label: string }) { return <div className="bg-foreground p-6 sm:p-8"><p className="display-type text-4xl text-secondary">{value}</p><p className="mt-2 font-mono text-[9px] uppercase tracking-widest text-background/50">{label}</p></div> }
