import type { ViralLaunch } from "@/lib/viral/types"

export const DEMO_VIRAL_LAUNCH: ViralLaunch = {
  id: "demo-launch-midnight-velocity",
  slug: "midnight-velocity",
  title: "Midnight Velocity / Global Breakout",
  artistName: "Nia Vale",
  trackTitle: "Midnight Velocity",
  trackAudioUrl: "/audio/beat2.mp3",
  objective: "Turn one irresistible drop into 500 distinct creator stories in 72 hours.",
  phase: "live",
  startsAt: "2026-08-07T00:00:00.000Z",
  endsAt: "2026-08-10T00:00:00.000Z",
  releaseAt: "2026-08-08T04:00:00.000Z",
  isPreRelease: true,
  bountyCents: 250000,
  creatorsActivated: 187,
  qualifiedPosts: 143,
  totalForks: 391,
  totalSaves: 4826,
  totalShares: 11640,
  creatorKFactor: 1.42,
  saveDestinations: [
    { platform: "spotify", url: "https://open.spotify.com/" },
    { platform: "apple", url: "https://music.apple.com/" },
    { platform: "youtube", url: "https://music.youtube.com/" },
  ],
  genomes: [
    {
      id: "genome-drop-confession",
      name: "Drop Confession",
      parentId: null,
      platform: "tiktok",
      niche: "Nightlife",
      hookStartSec: 42,
      hookDurationSec: 15,
      openingFrame: "Start on the consequence, not the setup.",
      pattern: "Confession -> tension hold -> beat-switch reveal",
      textBeats: ["I said I was staying in", "00:07", "The decision"],
      shotCount: 4,
      forkCount: 164,
      qualifiedActivations: 72,
      completionRate: 0.84,
      shareRate: 0.128,
      saveRate: 0.074,
      viralScore: 91,
    },
    {
      id: "genome-fit-check",
      name: "One-Beat Fit Check",
      parentId: "genome-drop-confession",
      platform: "instagram",
      niche: "Fashion",
      hookStartSec: 40,
      hookDurationSec: 15,
      openingFrame: "Freeze on the before look for exactly one beat.",
      pattern: "Before -> bass hit -> three-look acceleration",
      textBeats: ["The invite said casual", "I disagreed"],
      shotCount: 5,
      forkCount: 129,
      qualifiedActivations: 49,
      completionRate: 0.79,
      shareRate: 0.142,
      saveRate: 0.061,
      viralScore: 87,
    },
    {
      id: "genome-squad-switch",
      name: "Squad Switch",
      parentId: "genome-drop-confession",
      platform: "youtube",
      niche: "Dance",
      hookStartSec: 31,
      hookDurationSec: 15,
      openingFrame: "One creator enters frame on every kick.",
      pattern: "Solo -> handoff chain -> full-squad drop",
      textBeats: ["Pass the drop", "Do not break the chain"],
      shotCount: 6,
      forkCount: 98,
      qualifiedActivations: 22,
      completionRate: 0.88,
      shareRate: 0.096,
      saveRate: 0.082,
      viralScore: 84,
    },
  ],
  squads: [
    { id: "squad-afterhours", name: "Afterhours", identity: "Nightlife / Miami", captain: "@julesafterdark", memberCount: 18, qualifiedPosts: 31, score: 946, rank: 1 },
    { id: "squad-framebreakers", name: "Frame Breakers", identity: "Fashion / London", captain: "@mika.mov", memberCount: 14, qualifiedPosts: 24, score: 881, rank: 2 },
    { id: "squad-respawn", name: "Respawn", identity: "Gaming / Global", captain: "@roninplays", memberCount: 20, qualifiedPosts: 27, score: 834, rank: 3 },
  ],
  raids: [
    { id: "raid-signal-test", name: "Signal Test", phase: "test", startsAt: "2026-08-06T16:00:00.000Z", targetCreators: 20, activatedCreators: 20, status: "complete" },
    { id: "raid-niche-scale", name: "Niche Scale", phase: "scale", startsAt: "2026-08-07T16:00:00.000Z", targetCreators: 100, activatedCreators: 100, status: "complete" },
    { id: "raid-global-blast", name: "Global Blast", phase: "blast", startsAt: "2026-08-08T16:00:00.000Z", targetCreators: 500, activatedCreators: 67, status: "active" },
  ],
  unlocks: [
    { id: "unlock-stems", title: "Official stems", action: "forks", target: 500, current: 391, reward: "Instrumental and vocal stems release to every qualified creator.", unlocked: false },
    { id: "unlock-double-pool", title: "Double the pool", action: "saves", target: 5000, current: 4826, reward: "The artist doubles the final squad bounty.", unlocked: false },
    { id: "unlock-artist-room", title: "Artist enters the room", action: "posts", target: 100, current: 143, reward: "Nia reacts live to the five strongest branches.", unlocked: true },
  ],
  artistCommitments: [
    { id: "commit-reactions", label: "Creator reactions", target: 5, completed: 2 },
    { id: "commit-reposts", label: "Winner reposts", target: 3, completed: 1 },
    { id: "commit-live", label: "Live squad session", target: 1, completed: 0 },
  ],
}

export const DEMO_VIRAL_LAUNCHES = [DEMO_VIRAL_LAUNCH]

export function getDemoViralLaunch(slug: string): ViralLaunch | null {
  return DEMO_VIRAL_LAUNCHES.find((launch) => launch.slug === slug) ?? null
}
